### ISSUE TITLE
Coding & Documentation: American or British English?

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof_base#11]
As Caro mentioned, another decision has to be made about the spelling. This is quite fundemental and  should be written down in the documentation part  "How to document?".

I vote for British English since we are mostly located in and focused on Europe and the openmod-initiative already also uses British English.

**Comment by ckaldemeyer** [comment]
@gnn @simonhilpert @steffenGit @gplssm @birgits @caro-rli @cswh @uvchik @wolfbunke

**Comment by ckaldemeyer** [comment]
Is is actually possible to build groups here like in redmine "oemof-devs". It would be helpful to assign common issues and highlight issues..

**Comment by cswh** [comment]
I vote for british as well.

We have teams, and you should be able to mention them as @oemof/oemof-main as it is now.

**Comment by uvchik** [comment]
:+1:  BE

**Comment by gplssm** [comment]
AE

**Comment by birgits** [comment]
In my opinion it doesn't matter too much as both British and American wording and spelling is equally comprehensible. The only thing I find important is the spelling of "model(l)ing" since it is part of the name.

**Comment by ckaldemeyer** [comment]
"The only thing I find important is the spelling of "model(l)ing" since it is part of the name."

So what's your opinion here? ;)

**Comment by wolfbunke** [comment]
Let's say British English with exception to "modeling". In fact it doesn't matter it should be only consistent.

**Comment by uvchik** [comment]
But this is the case. By now it is not consistent. The pages (github, wordpress, rli-homepage) have the british spelling (modelling). The Logo has the AE-spelling. In the documentation you can find both "modelling" and "modeling".

I would say BE and "modelling".

How do we bring this to an end? Just vote?

@birgits: square
@ckaldemeyer: BE
@cswh: BE
@wolfbunke: BE but the word "modeling" in AE
@uvchik: BE
@gplssm: AE

@gnn, @caro-rli, @simonhilpert: Please vote!

**Comment by caro-rli** [comment]
I vote for 'modeling'.

**Comment by ckaldemeyer** [comment]
I don't get one thing:

What's the point of using "modeling" (which is de facto AE) in combination with BE?

For me this would be only inconsistent and also breaks with the openmod-spelling. Even if I can understand the usage for aesthetic reasons..

**Comment by ckaldemeyer** [comment]
Btw: I am for BE and "modelling" if that hasn't come clear ;)

**Comment by simonhilpert** [comment]
i do not care (BE modelling is fine for me)

**Comment by ckaldemeyer** [comment]
@birgits: square
@ckaldemeyer: BE
@cswh: BE
@wolfbunke: BE but the word "modeling" in AE
@uvchik: BE
@gplssm: AE (modeling)
@caro-rli: "modeling"
@simonhilpert:: BE

Modelling: 4
Modeling: 3

@gnn, Please vote!
@birgits : BE or AE? Modelling or Modeling?

**Comment by birgits** [comment]
I don't care either way, but just to end this discussion I vote for "Modelling" :)

**Comment by ckaldemeyer** [comment]
A Decision has been made: BE +"Modelling"

**Comment by uvchik** [comment]
@wolfbunke : Will you change the Logo?

**Comment by gnn** [comment]
BE. All the way.

**Comment by uvchik** [comment]
The new logos can be found on: http://vernetzen.uni-flensburg.de/~git/oemof_logos/
