### ISSUE TITLE
Who will be additional owner of in oemof?

### ISSUE THREAD

**Issue by cswh** [oemof/oemof_base#12]
Decision wanted from: @oemof/oemof-main .

I think we should add owner with admin rights - e.g. for small changes in between and not only relying on two people.

Who wants to be owner and take some responsibilty for the group-page, as well as this repository on github? I propose @ckaldemeyer .

**Comment by uvchik** [comment]
I can give admin rights to both of you, if you like.

In the next time it will be nothing more than adding new people and so far we do not have an agreement how we will decide about writing access.

**Comment by ckaldemeyer** [comment]
Clemens and Cord now have admin rights
