### ISSUE TITLE
Check docstring of Simulation class

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#13]
@simonhilpert: May you have a look at the docstring of the [Simulation class](../blob/features/revise_docstrings/oemof/core/energy_system.py#L157)?

I do not understand some attributes. Do not care for the layout. I will do that later.

**Comment by simonhilpert** [comment]
I added the docstrings.

**Comment by uvchik** [comment]
:smile: Thanks.

**Comment by uvchik** [comment]
@simonhilpert, @cswh May any of you have a look at the [Bus class](../blob/features/revise_docstrings/oemof/core/network/entities/__init__.py#L4). There are some parameters I do not know. Thanks in advance.

**Comment by simonhilpert** [comment]
I completed the docstring in the bus class

**Comment by uvchik** [comment]
Great :smile:
