### ISSUE TITLE
How to connect a power plant to an existing bus

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#17]
Example: Natural gas power plant

To define the simple transformer, i have to pass the bus objects. So I have to find them in the list of entities of the energy system. As far as I understood oemof, all entities are automatically written to the list of entities in the object of the EnergySystem class.

As you suggested I am using tuples to identify the entities.

```python
# Creating the energy system
ExampleSystem = es.EnergySystem()

# Creating regions
ExampleSystem.regions.append(es.Region(geom=GeoObj1, name=region1))
ExampleSystem.regions.append(es.Region(geom=GeoObj2, name=region2))

# Creating a global gas bus
Bus(uid=('bus', 'global', 'ngas') , type='ngas', price=60, sum_out_limit=10e10)

for region in list_of_regions
    # Creating a electricity bus for each region.
    Bus(uid=('bus', region.name, 'elec') , type='electricity', price=60, sum_out_limit=10e10, regions=[region])
    
    # Creating a gas power plant for each region
    transformer.Simple(
            uid=('ngas_power_plant', 'region.name', 'ngas', 'elec'),
            inputs=ExampleSystem.entities[??????],  # Global gas bus
            outputs=ExampleSystem.entities[??????],  # Local electricity bus
            in_max={('bus', 'global', 'elec'): None},
            out_max={('bus', region.name, 'elec'): 10000},
            eta=[0.4])

**Comment by simonhilpert** [comment]
first: inputs/outputs have to be lists

I usually extract the bus by the uid of the bus before instantiating the object:

inputs = [obj for obj in ExampleSystem.entities if obj.uid == ('bus', region.name, 'elec')]
transformer.Simple(...

Mayby @gnn has a better idea 

By the way in_max / out_max do not get dicts but lists  (v0.0.1)
so i would be enough to do: 

transformer.Simple(...,
in_max=[None]
out_max={[10000],
eta=[0.4])

**Comment by uvchik** [comment]
I thought @gnn said at the meating in FL, that there is a simple way to find entities in the list of entities.

For example all transformers or all electric storages or all electric buses or all electric buses within a given region....

**Comment by simonhilpert** [comment]
Ok, well I guess with the 'region' attribute you could check:

[obj for obj in entities if obj.region == 'region_to_check'] 

or you could check for: type(obj) isinstance(tranformer.Simple)

But I get your point, if @gnn  has a better idea than just looping over all entities every time (or at least once) am excited...

**Comment by uvchik** [comment]
@simonhilpert : I think you are right. Maybe I misunderstood something.

@gnn : May you check this and close the issue?

**Comment by uvchik** [comment]
So far there is no better solution but @gnn will create a new access (see issue #60).
