### ISSUE TITLE
Abstract Base Class Attributes 

### ISSUE THREAD

**Issue by simonhilpert** [oemof/oemof_base#18]
We already had some discussions about the attributes and their meaning of the base-class objects. 

At the moment we are using a mix of well known economic notations such as opex, capex etc. 
and technical parameters that refer to the graph nature of out energysystem model (in_max, out_max, etc)

I talked to @gnn and @ckaldemeyer and if I got it right, it might be a good idea to have abstractly named attributes to be consitent with the general representation as a graph. 

Starting with an example: 
Replacing the attributes: 

```python 
self.in_max = ..
self.out_max = ... 
self.in_min = ... 
self.out_min = .. 
self.add_out_limit = .. 
```
by bounds:: 

```python
self.bounds = kwargs.get('bounds',
                                     {'inflow': [None, (None, None), None],
                                      'outflow': [None, (None, None), None]}
```    
Additionally for economic parameters: 

```python
 self.costs = kwargs.get('costs', {'inflow':  None,
                                          'outflow': 0,
                                          'ramping': {'up': None,
                                                           'down': None},
                                          'startup': None,
                                          'shutdown': None,
                                          'capital': None,
                                          'fix' : 0,
                                          'wacc': 0.05})
```
With such a (or a similar) structure we could allow for very individuell modeling of the energysystems
without having a huge amount of different attributes. I think in a mid-term perpective we should 
move in this direction, maybe it is a good idea to do so before all apps etc. are finished? 

What do you think: @gnn @ckaldemeyer @uvchik @cswh @caro-rli ?

**Comment by simonhilpert** [comment]
I actually added a branch with my ideas: 

simonhilpert@13dd18828523d298e35ae7d30f5ca377f2ded535

**Comment by ckaldemeyer** [comment]
I have looked at your ideas and think that it absolutely makes sense to go in this direction. But if the attributes get more *abstract* it very important to have a *concrete* application example for new users.

@cswh @gnn  : if that's not too much effort, it would also make sense use these attributes in renpass-gis directly, or not?

I would offer myself to make the changes. Maybe we can also discuss this on Thursday together with Simon based on the comments made here..

**Comment by gnn** [comment]
Sorry. Wasn't available for discussion today. What about friday?
FWIW I think renpassgis should use the "old" format with lots of attributes, the reason being that renpassgis isn't tied to the progress on this. Then we can take our time to get this right and renpassgis is a nice example for whether whatever we come up with handles all use cases appropriately.

**Comment by simonhilpert** [comment]
Today we already decided in a similar way. I will close this issue and delete the feature branch. The idea
is to take this kind of development to a new repository.

**Comment by uvchik** [comment]
Does "new repository" means a fork?

I do not survey all consequences but if it is an improvement a feature branch should be the right place.

**Comment by simonhilpert** [comment]
no, new repo means completely new repo (even not fork)...improvements will of course take place in oemof_base repo.
