### ISSUE TITLE
Entity does not appear in the EnergySystem object

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#19]
I created an EnergySystem object and than created a bus. This bus should automatically appear in the entities list of the EnergySystem but it does not.

Do I have to pass the EnergySystem to the entity?

So far it looks like this:
```python
Bus(uid=('bus', 'global', 'coal'), type='coal', price=60, sum_out_limit=10e10)
```

**Comment by gnn** [comment]
Ok, closing by comment didn't work as expected.
@uvchik could you check whether it works for you now? It should.

**Comment by uvchik** [comment]
Maybe it needs to be in the commit message and not in the commit comment to close the issue.

https://help.github.com/articles/closing-issues-via-commit-messages/

I will check the fix and give a feedback soon.

**Comment by uvchik** [comment]
Seems to work. Thanks a lot.
