### ISSUE TITLE
Old versions on pypi

### ISSUE THREAD

**Issue by EvaWie** [oemof/oemof_base#21]
On pypi are links to old versions that are not available. Do we want to delete them?
https://pypi.python.org/pypi?%3Aaction=search&term=oemof&submit=search

**Comment by uvchik** [comment]
I do not know how to that. If you do know, go ahead.

**Comment by uvchik** [comment]
@oemof/oemof-main Do we want to do anything about it or just ignore it?

Maybe there is a way to remove it from the pypi-index but I couldn't find anything quick. I would ignore it and will close this issue within a week if nobody will complain.

**Comment by uvchik** [comment]
Since three weeks nobody has cared about this.
