### ISSUE TITLE
Change default repository

### ISSUE THREAD

**Issue by MGlauer** [oemof/oemof_base#22]
You discussed your git workflow on your release meeting and semi-decided in favor of the common git-flow. This flow changes the meaning of the master branch from a "main"-branch to a "latest-release"-branch that is relatively outdated. Yet, it is the first branch that you visit on your git-hub.  

It might be useful if you change the default branch from master to develop.

**Comment by ckaldemeyer** [comment]
Good point. +1

**Comment by uvchik** [comment]
:+1:

**Comment by ckaldemeyer** [comment]
The default repo can be changed easily if all members aggree: https://help.github.com/articles/setting-the-default-branch/

**Comment by ckaldemeyer** [comment]
Since no one objected to the issue I have now changed the default branch to "dev".
