### ISSUE TITLE
Delete an orphan Bus

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#23]
I created a lignite resource bus by hand but there is no lignite power plant in my region.

So I check all buses and want to delete the orphan ones. The following doesn't work:

```python
buses = [obj for obj in MyEnergySystem.entities if isinstance(obj, Bus)]
for bus in buses:
    if len(bus.inputs) > 0 or len(bus.outputs) > 0:
        logging.debug('Bus {0} has connections.'.format(bus.type))
    else:
        logging.debug('Bus {0} has no connections and will be deleted.'.format(
            bus.type))
        MyEnergySystem.entities.remove(bus)
```

I assigned it to @gnn but maybe anybody else has an idea (@cswh, @simonhilpert, @ckaldemeyer).

**Comment by simonhilpert** [comment]
remove only 'deletes' the object (ref. to object) from the list. If you want to delete the object itself you I think you need to use:  

```python 
del obj 
```

**Comment by uvchik** [comment]
I could not delete the object using ```del obj``` but I found out that removing the object from the list is actual all that I want. If I remove the entitiy from the list, solph will not find it and therefore will not process it.
I just want to prevent solph from processing orphan entities even though it might not have a negative impact on the performance.

Thanks anyway :smile:
