### ISSUE TITLE
Complete oemof's on Wordpress

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof_base#24]
The wordpress page (https://oemof.wordpress.com/) still has to be completed. I would keep it pretty lean with a standard text and contact details.

If you have other ideas/wishes, you can post it here!

@oemof/oemof-main

**Comment by uvchik** [comment]
What about a post after every release. As I am the person in charge for the next release I will do that for the 12-2015 release.

**Comment by ckaldemeyer** [comment]
Sounds good. This could include the bugfixes, new features, ...

**Comment by uvchik** [comment]
...therefore everybody should fill out the what's-new-section in the documentation (see #15).

**Comment by uvchik** [comment]
Please help with posts of any kind. 

* BlaBla project uses oemof...
* oemof presentation at...

@gplssm What about London. Just two sentences and a link?

Even historical posts are okay. You can change the publishing date of the post to an elapsed date.

I uploaded the logo (https://oemof.wordpress.com).

**Comment by ckaldemeyer** [comment]
Looks nice. I'll update "libraries" and "contact" in the next days

**Comment by ckaldemeyer** [comment]
I have updated the contact page, the github link, the link to the documentation and removed the redmine-link which is in my opinion not necessary.

In my opinion the page "Downloads" can be removed since everything which is feedinlib-related is available on github anyway.

The latest documentation is not up to date. Should we merge the latest fixes from the dev branch into the master?

Have a nice weekend!

**Comment by gplssm** [comment]
Nice work!
I can offer do write a few lines about the breakout group in London. Oemof was part of discussion there, but the focus was on the _OpenEnergy Platform_ (see [slides](http://wiki.openmod-initiative.org/wiki/File:09_-_Guido_Ple%C3%9Fmann_-_2015_09_09_OpenEnergy_Platform_Guido.pptx)). Do you think it is interesting for the blog? If so, i'll do it. How can I write a new post on the blog, who has access rights?

**Comment by ckaldemeyer** [comment]
I think the blog would be the right place for all activities around oemof and the openmod-discussion would be a good starter!

You should have a wordpress invitation in you mailbox ;)

**Comment by uvchik** [comment]
@gplssm : Will you be able to do this before Christmas?

**Comment by gplssm** [comment]
today ;)

**Comment by gplssm** [comment]
...done (:

**Comment by uvchik** [comment]
@gplssm Thanks :smile: 

I update the *library* page: https://oemof.wordpress.com/libraries/

@oemof/oemof-main Could anybody proofread it?

**Comment by caro-rli** [comment]
I read it and corrected some typos. What about the sentence: "Solph uses *python* to create linear problems which can be solved.." Is pyomo meant?

**Comment by caro-rli** [comment]
but.. what's the trick to save changes?

**Comment by uvchik** [comment]
Yes, "pyomo" not "python" :+1:

**Comment by caro-rli** [comment]
ok, found the trick with saving.

**Comment by uvchik** [comment]
I had to change the wp layout, because the old one was not suitable for smartphones and tablets.

If you don't like it, feel free to change it. But I promise you it is very annoying.

**Comment by ckaldemeyer** [comment]
Looks nice! But the Logo still (or again) says "modeling". Is this by purpose?

**Comment by uvchik** [comment]
Fixed.

**Comment by uvchik** [comment]
The logos can be found on: http://vernetzen.uni-flensburg.de/~git/oemof_logos/

**Comment by uvchik** [comment]
Everything works by now, so I will close this issue.

Keep in mind to keep the wordpress side alive!

Open a new issue for special tasks.
