### ISSUE TITLE
Which versions do we want to have at readthedocs (RTD)?

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#30]
Do we get a decision until the next release? Would be great :smile: 

1. Which branches do we want to show?
2. What should be the default branch?

There is no fall-back at RTD. If somebody links to .../en/dev and this link doesn't exist anymore an error is shown. Therefore I think it is good to decide soon.

Beside the feature branches we can offer documentations for the following branches/labels:

**I did not find a way to change the references of latest and stable!**

name |  description
--------|----------------
latest | ~~master-branch~~ (edit: dev-branch)
stable | last version label (now: v0.0.1, next week: v0.0.2)
v.0.0.1, v0.0.2, ....| all versions we do release
dev | dev-branch
master | master-branch

**Comment by uvchik** [comment]
1. I would use latest (stable with hotfixes), the last x versions (according to pip install) and dev (the most actual changes).
2. The default should be the dev branch as there is another unchanged documentation on the pypi-page (pythonhosted.org).

**Comment by ckaldemeyer** [comment]
I'm with Uwe's proposal.

**Comment by uvchik** [comment]
Sorry. I found out, that it is possible to point the "latest" flag to different branch. 

1. I would use latest (the most actual changes) and the last x versions (according to pip install) and stable (the last stable version).
2. The default should be the dev branch (latest) as there is another unchanged documentation on the pypi-page (pythonhosted.org).

**Comment by ckaldemeyer** [comment]
+1

**Comment by uvchik** [comment]
As nobody commented this issue I will implement it as defined above for the December release.

I will close this issue until anybody will object.
