### ISSUE TITLE
Github issue filter for mentions group

### ISSUE THREAD

**Issue by cswh** [oemof/oemof_base#42]
Does anyone know how to filter the issues to show all issues where a group is mentioned?
* `mentions:cswh` works
* `mentions:oemof/oemof-main` does not work
The function would make it much easier in my opinion to filter for relevant issues which need "urgent attention". If it does not work, we should have some better rules for the use of labels. So far there are no rules for labelling issues and everybody does it as he feels like?

**Comment by uvchik** [comment]
`team:oemof/oemof-main`

**Comment by uvchik** [comment]
https://help.github.com/articles/searching-issues/

**Comment by cswh** [comment]
Thanks a lot!
