### ISSUE TITLE
Simulation-object for solve-method of optimizationmodel not working from outside energysystem class

### ISSUE THREAD

**Issue by simonhilpert** [oemof/oemof_base#43]
At the moment the simulation-object only works in combination with optimize method of the energy_system class. I should work as well from outside the energysystem if the solve method is called for the optimization model. 

I added this (removed again) inside the sovle-method of OptimizationModel() in the solph package as an
idea: 
```
        debug = kwargs.get('debug', self.energysystem.simulation.debug)
        duals = kwargs.get('duals', self.energysystem.simulation.duals)
        solver = kwargs.get('solver', self.energysystem.simulation.solver)
        solver_io = kwargs.get('solver_io',
                               self.energysystem.simulation.solver_io)
```

**Comment by ckaldemeyer** [comment]
It might be a bit off-topic but I have just adjusted the storage_optimization example came across the following:

    simulation = es.Simulation(timesteps=timesteps, stream_solver_output=True,
                               objective_options={
                                   'function':predefined_objectives.minimize_cost})

    energysystem = es.EnergySystem(entities=entities, simulation=simulation)
    energysystem.year = 2010

    om = OptimizationModel(energysystem)
    om.solve(solver='gurobi')

The simulation object and direct passed parameters are still co-existing. We should go one way and fix it in the next version.

**Comment by simonhilpert** [comment]
I disagree, both way should stay possible. That's what this issue is for. If one uses simulation object - fine if not use solve() method and pass parameter. Or use simulation object for some options and adjust when calling solve().
But the simulation-object attributes should be passed to solve() method in every case. This is only true for the use of optimize() method from the energysystem class. 
Actually setting the attribute  'stream_solver_output' at the example above should not change anything at the moment because it isn't implemented this way...

**Comment by ckaldemeyer** [comment]
Convinced

**Comment by simonhilpert** [comment]
I actuaclly checked today in the storage example and solver output is not streamed due to the 'bug' even if it's set at the attribute of simulation object....

**Comment by simonhilpert** [comment]
I set the milestone to January release, is this realistic ? @gnn

**Comment by simonhilpert** [comment]
I can go ahead with this one @gnn

**Comment by simonhilpert** [comment]
I fixed the bug for now, it is not perfect, but i works as intended. Now the simulation object attributes are taken if the solve() method does not have any...
