### ISSUE TITLE
sudo pip3 install oemof, import oemof not working

### ISSUE THREAD

**Issue by s3pp** [oemof/oemof_base#44]
Tried to install oemof with "sudo pip3 install oemof". Everything seems to work fine, no errors, but import oemof in python got me a "no module named oemof" error. Downloading the zipped package and installing with "pip3 -e /path" worked fine, import oemof also. Do I have to adjust some environment variables when installing otherwise?

**Comment by s3pp** [comment]
The command was actually "sudo pip3 install oemof_base", forgot the underscore base. Importing the module in python still failed.

**Comment by uvchik** [comment]
This is confusing. Maybe we should change this.

The name of the package on github or pypi is oemof base but is installed as oemof. Have a look at the storage_invest example. There you can see how imports work.

```python
from oemof.core import energy_system as es
```

Try the example but change [line 147](../blob/dev/examples/storage_optimization/storage_invest.py#L147) if you do not have Gurobi installed.

For testing purpose you could install the glpk solver: https://www.gnu.org/software/glpk/

`solver='glpk'`

Does the example works for you?

**Comment by s3pp** [comment]
The import of oemof in python worked fine when installing with 'sudo pip3 install -e /path/oemof_base-dev' (downloaded from github), also storage_invest.py runs without problems (thanks for the hint to use the 'glpk' solver). Just the import of oemof in python after installing it with 'sudo pip3 install oemof-base' as stated in the docs resulted in the missing module error.

**Comment by uvchik** [comment]
As it works for you it is not urgent, right? 

* What happens if you import oemof_base?
* What is the output of `pip3 list` (not whole list, but the oemof specific part)?

@ulfmueller Do you had the same problems lately? (#38)
@gnn Do you have an idea?

**Comment by ulfmueller** [comment]
yes I had the exact same problem and I performed the same work around as @s3pp ....

**Comment by s3pp** [comment]
No, its not urgent, I was just wondering!
retrieved with pypi:

pip3 list | grep oemof
oemof-base (0.0.2.1)

...import oemof or import oemof_base in python fails.

**Comment by uvchik** [comment]
Thank you for the report @s3pp, we will try to fix it.

**Comment by uvchik** [comment]
I found out that `import oemof_base.oemof` works.

@gnn : Don't you think it is the same problem we had when we used the `src` folder?

I opened a new issue (#45) to discuss the renaming of the folder to avoid such errors.

**Comment by nesnoj** [comment]
same problem here when using 'sudo pip3 install oemof-base', gonna use workaround too

**Comment by gnn** [comment]
The problem is different to the one that occured when we where using `src` as the source folder.
I was able to reproduce the current issue though when trying to install from a local source distribution generated via `python setup.py sdist`.
Commit 4a371d7 fixed it for me
@uvchik: Could you check whether it also works locally for you? If so we could upload a `0.0.2.2` version (now that we have a fourth version number anyway) and see whether that fixes things for everybody else too.

**Comment by uvchik** [comment]
I tested it, uploaded the version `0.0.2.2` and tested the uploaded version. Works now. Thank you :smile:
