### ISSUE TITLE
REMINDER: January Realse Nose Tests!

### ISSUE THREAD

**Issue by simonhilpert** [oemof/oemof_base#47]
@oemof/oemof-main: 
The January release has a focus on test. This is just a reminder for all developers that test have to be 
written!

**Comment by uvchik** [comment]
I fixed a wrong doctest. You can write doctests in your docstring as it is done [in the linear_constraints module](../blob/dev/oemof/solph/linear_constraints.py#L17).  These are tests and examples in documentation.

Or you can use the test folder and create your own testing module or use the [existing module](../blob/dev/tests/basic_tests.py). These test are just test.

To execute the test use `nosetests3`.

```bash
cd /path/to/oemof_base/
nosetests3 --with-doctest
```

I like the rednose option but you do not need it. It brings some colors :smile: 

```bash
cd /home/uwe/git/oemof_base/
nosetests3 --with-doctest --rednose
```

To see more examples for tests, have a look at the feedinlib.

@oemof/oemof-main : What about one test for everybody until the January release :interrobang:

**Comment by ckaldemeyer** [comment]
:+1:
