### ISSUE TITLE
Storage model in investment mode: some understanding problems

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof_base#49]
Hi there,
even though I was involved in the development of the storage functionalities, I still have some problems in understanding.. I have an investment model with storage component and without any constraints concerning upper and lower bounds, so my storage component definition would look like this.. only buses, technical and economic parameters are given:

```python
storage = transformer.Storage(uid='sto_simple',
                              inputs=[bel_hh],
                              outputs=[bel_hh],
                              eta_in=1,
                              eta_out=0.8,
                              cap_loss=0.00,
                              opex_fix=35,
                              opex_var=10e10,
                              capex=1000,
                              cap_initial=0,
                              c_rate_in=1/6,
                              c_rate_out=1/6)
```

I get this error:

```
  File "/home/caro/rlihome/Git/oemof_base/oemof/core/network/entities/components/transformers.py", line 170, in __init__
    'Did you specify c_rate_out and cap_max?')
ValueError: Failed to set out_max automatically.Did you specify c_rate_out and cap_max?
```

.., because I didn't specify cap_max, which is the maximum value of state of charge (as absolute value), means the storage capacity.

As far as I understand, cap_max is necessary here to calculate out_max (c_rate * cap_max), which is the maximum output value in every timestep and an attribute for every component. So I have to either define out_max or cap_max when creating my storage object. But since I have an investment model, those two attributes are variables in my case and I want to let the model calculate them.

I really don't get it :-(
What is my mistake here?

@simonhilpert 
@ckaldemeyer

**Comment by ckaldemeyer** [comment]
I assume you're on the dev-branch. This is something I stumpled upon with @gnn on Friday. I also don't like the name "cap_max" and "cap_min" for the energy of the storage since it can be confused with "installed capacity".

Concerning your problem:

Normally solph should create additional variables if *investment* is set to *True*. Have you analyzed  your results? Using outputlib you could have a look at the result dataframe and see the capacities and storage SOC which is put into "other" in the bus the storage has as its output.

**Comment by simonhilpert** [comment]
This is not an solph issue. In the transformers.Storage() class an ValueError is raised, which should not if the investment 'flag' is set. I think there is no easy way to change this. 
Quick an dirty: just replace the ValueError by a logging.Warning or comment this lines. I will try to fix this issue as soon as possible...

**Comment by simonhilpert** [comment]
Or just set cap_max to zero, in this way it's possible to calculate out_max/in_max (values are 0 then) 
But inside your constraints for the investment storage constraints these values aren't used anyway.

**Comment by ckaldemeyer** [comment]
@simonhilpert : Just to get this right. If *cap_max* is set and investment set to True, solph "ignores" *cap_max*, or not!?

**Comment by ckaldemeyer** [comment]
Ah, you were faster... ;)

**Comment by simonhilpert** [comment]
no because it is used in: 

oemof.solph.linear_constraints.add_storage_charge_discharge_limits

(how can I post a link?) 

But I did a small fix which I will push on the dev branch...this will solph the problem for now...

**Comment by simonhilpert** [comment]
@caro-rli : pushed...try if it works now

**Comment by ckaldemeyer** [comment]
this means that only the installed capacity is unbound and the energy
always fixed?

Am 11.01.2016 um 16:51 schrieb simonhilpert:

**Comment by simonhilpert** [comment]
i do not understand....cap_max is the build capacity of the storage, if investement is this amount 
can be . this is done with the variable 'add_cap'. 
The after optimization has taken place the storage capacity installed is: cap_final = cap_max + add_cap

**Comment by ckaldemeyer** [comment]
that was the answer to my question: the storage capacity (energy) can be increased if investment is set to True. 

i just don't like the term *capacity* for an "amount of energy" since it can be ambiguous with "installed capacity". to me it should be either "power" and "capacity" or "capacity" and "(amount of) energy".

**Comment by simonhilpert** [comment]
yeah feel free to improve.. ;)

**Comment by caro-rli** [comment]
Oh, discussions is going on.. thank you :) I have the everyday problems on my computer right now, so can't test it directly, but this explanation

>cap_max is the build capacity of the storage, if investment is true, this amount
can be increased . this is done with the variable 'add_cap'

helps already.

**Comment by caro-rli** [comment]
>to me it should be either "power" and "capacity" or "capacity" and "(amount of) energy"

or "state of charge", but this is per definition (as far as I know) the percental value based on the installed or usable capacity.

What I was confused about was the term "max" in context with the built capacity.
But this all seems to be a question of naming.

**Comment by caro-rli** [comment]
@simonhilpert : works now with your commit, thanks!

**Comment by uvchik** [comment]
@caro-rli : Would you add your awarenesses to the documentation?

**Comment by ckaldemeyer** [comment]
>     to me it should be either "power" and "capacity" or "capacity" and
>     "(amount of) energy"
>
> or "state of charge", but this is per definition (as far as I know)
> the percental value based on the installed or usable capacity.
>
I share this definition of SOC and thus for me it would be no option for
the amount of energy.
>
> What I was confused about was the term "max" in context with the built
> capacity.
> But this all seems to be a question of naming.
>
I guess cap_max was used since cap_min exists and there might be an
option where the SOC ist only allowed to oscillate between these two values.

**Comment by simonhilpert** [comment]
actually long term goal of base-classes will be general attribute on top-level, similar to : 
```
bounds = {'inflow': [0, (10, 100), None],
          'outflow': [0, ([None, None], [200, 100]), float('+inf')]} 
 
costs = {'inflow':  10,
         'outflow': 10,
         'ramping': {'up': None, 'down': None},
         'startup': None,
         'shutdown': None,
         'capital': None, 
         'wacc': 0.05}

revenues = {'inflow': None, 
            'outflow': None} 

co2 = {'inflow': None,
       'outflow': 0.220, 
       'investment': 

lifetime = 20 
```

Then constraints will be set based on the set attributes in solph...at least this was an idea of @gnn 
and me. More speaking names could then be used for specific energy - components. 

If we don't want to go this way we should just have a decision about the naming of all existing attribute (because i do  think that most of the names are not very good as well). 

what do you think @oemof/oemof-main

**Comment by ckaldemeyer** [comment]
For me this seems to be something for the web conference as it affects many things.

**Comment by ckaldemeyer** [comment]
What do you mean by "long term goal of base-classes will be general attribute on top-level"?

Your example shows how (a dict) but where will the dict be stored? Or will it be generated from the classes?

**Comment by simonhilpert** [comment]
I mean that we want to change in future and resolve some naming conflicts (such as them 
we are discussing here)
top level i mean only inside the top base classes. (transformer, transport, source, sink)

it would be placed e.g. inside the transformer.Simple()  __init__() method...

**Comment by ckaldemeyer** [comment]
Ah, ok. Sound like a good idea to me. Maybe we can do this in one go with the unique class names and revise the docstrings, too. Shall we create an issue for this?

**Comment by uvchik** [comment]
@caro-rli : Could you just complete the documentation and close the issue, when you are finished.

**Comment by caro-rli** [comment]
I added some little more information about cap_max in the docstring. Closing this issue now.

**Comment by simonhilpert** [comment]
I saw the docstring and I think it is not correct. 

`absolut maximum state of charge of built capacity if invest=TRUE` is not cap_max but add_cap_limit

cap_max is the maximum state of charge of existing capacity prior optimization.

**Comment by caro-rli** [comment]
With

>built capacity

I meant the already installed capacity. I can use other words to make it more clearly.
What do you mean with prior optimization?

I think the maximum state of charge of storage capacity in total cannot be known before. Isn't add_cap_limit only the limit and "built" capacity (after optimization) can be below this value?

**Comment by simonhilpert** [comment]
by prior I mean the installed capacity without optimization. 

add_cap_limit only bounds the additional built capacity and not the total of cap_max + add_cap

**Comment by caro-rli** [comment]
ok, I'll change the wording tomorrow
