### ISSUE TITLE
Finish first version of demandlib

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof_base#5]

**Comment by uvchik** [comment]
The code for the heating demand only exists in this branch. Do not remove this code before merging.

**Comment by uvchik** [comment]
Is it planed for the December release or later?

**Comment by caro-rli** [comment]
I plan it for a later release, but want to do the last changes to function with new oemof structure (equivalent to feedinlib) as soon as possible, so that other users (open ego team?) can test it until release. Does that make sense?

**Comment by uvchik** [comment]
May you define which part of the demandlib will be part of the December release and create an issue with the December milestone. If the part is ready to test it should be part of the release.

**Comment by caro-rli** [comment]
is now in features/demandlib and works so far with two examples (oemof_base/examples/example_demandlib.py)

**Comment by caro-rli** [comment]
I suppose, open task for me is to bring it to the dev branch.. ?

**Comment by caro-rli** [comment]
merged and pushed.

**Comment by uvchik** [comment]
Some problems occurred with the merge of the demandlib

* the demandlib is above the toplevel
* old files that where removed months ago occurred again (example.py, energy_regions...)
* the module energy_buildings seems to be part of the demandlib but is placed in the core package

@caro-rli : will not be at work until next week, so we could either remove the merge commit or try to fix it until Friday.

**Comment by uvchik** [comment]
I hope I fixed all of it. If you still find odd things please check against commit 3f328e12db. This is the merge of the demandlib.

**Comment by ckaldemeyer** [comment]
:+1: Thanks!

One thing which is not related to this topic. I just saw a header like this:

<code>
"""
+Created on Fri Jul 24 19:11:38 2015
+
+@author: caro
+"""
</code>

I think at some stage (maybe also the remastering in February) we should get rid of all personal (Spyder) headers, etc. in the code.

**Comment by uvchik** [comment]
@ckaldemeyer : Totally agree. Just didn't dare to remove it from anybody else.

**Comment by uvchik** [comment]
Shall we start an issue to collect all the topics for the remaster process?

**Comment by ckaldemeyer** [comment]
Yep! I'll create one.

**Comment by uvchik** [comment]
Thank you. Guess that's all for this issue. @caro-rli owes me a beer :smirk:

**Comment by caro-rli** [comment]
Thanks a lot!! :blush:
