### ISSUE TITLE
No investment in sources when add_out_limit is omitted

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof_base#53]
When I run the storage_invest.py with

```python
source.FixedSource.optimization_options.update({'investment': True})
```
and no add_out_limit in the FixedSources pv and wind I get the following in lp file

```
0 <= _class__oemof_core_network_entities_components_sources_FixedSource___add_out(pv) <= 0
0 <= _class__oemof_core_network_entities_components_sources_FixedSource___add_out(wind) <= 0
```

which is wrong in my opinion since there is no possibility for the add_out variable to increase.

When I then in addition set out_max=[0] I get an infeasible problem as there can't be any generation capacity to meet the demand.

I pushed the modified storage_invest.py to the branch 'fix_invest_sources'.

**Comment by caro-rli** [comment]
Ok, I take everything back. When I set add_out_limit to a very high value, like 10e20, I get

```
0 <= _class__oemof_core_network_entities_components_sources_FixedSource___add_out(pv) <= 1e+21
0 <= _class__oemof_core_network_entities_components_sources_FixedSource___add_out(wind) <= 1e+21
```

in the lp file and a feasible problem. I wonder if that is the intended approach.

**Comment by simonhilpert** [comment]
0 is the default value for the `add_out_limit` attribute of FixedSource class (and other classes that have the attribute.) 
 
If it is fixed now please close the issue.

**Comment by caro-rli** [comment]
I removed the default value for the add_out_limit. For an investment model you can omit the add_out_limit now. No errors when running an investment model, so I'm closing this issue now.
