### ISSUE TITLE
Doctest only works locally

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#57]
The problem is that it is not possible to set a "wildcard" at the beginning of a doctest. I found a workaround that works locally but it doesn't work with nosetests. I use the following command:

```bash
nosetests3 --with-doctest --rednose --doctest-options '+ELLIPSIS'
```

The doctests looks like this:

```python
>>> import logging
>>> from oemof.tools import logger
>>> logger.define_logging()
[...]INFO-Path for logging:...
[...]INFO-Used oemof version:...
>>> logging.debug("Hallo")
```  
```
Expected:
       [...]INFO-Path for logging:...
       [...]INFO-Used oemof version:...
   Got:
       17:56:51-INFO-Path for logging: /home/uwe/.oemof/log_files
       17:56:51-INFO-Used oemof version: 8fc3f5bc@features/use_logging
```

A doctest that works from 10am to 8pm looks like the following:

```python
>>> import logging
>>> from oemof.tools import logger
>>> logger.define_logging()
1...
1...
>>> logging.debug("Hallo")
```  

The "ELLIPSIS" works if there is at least one character before. As this is the time it doesn't work for 20:34 or 09:34 but it works for 11:34. That's no option, I just wanted to show the problem. The solution to solve it locally is from http://stackoverflow.com/questions/5812833/can-i-have-an-ellipsis-at-the-beginning-of-the-line-in-a-python-doctest

I like it to have the example in the docstring. But if it is not possible I could change the design of the doctest, that it is not recognized as a doctest and add the test in the testing folder where it is possible to get the actual time.

@gnn : Do you haven an idea?

**Comment by uvchik** [comment]
See the `use_logging` branch to test it.

**Comment by simonhilpert** [comment]
Do we merge `use logging` for the next release? I have made some changes on the branch (that are actually not to be placed there, and I do not know why I did this - but I did)

**Comment by uvchik** [comment]
I think it is not worth to spend to much time in fancy doctests. Normally it is no problem to create a working doctest. If the doctest contains an user-specific output you have to use ellipses (`...`).

In this special case the ellipses are needed at the beginning of the line and this is not possible. So just skip the doctest and create a test in the testing folder. So the example from above now looks like this:

```python
>>> import logging
>>> from oemof.tools import logger
>>> logger.define_logging() # doctest: +SKIP
17:56:51-INFO-Path for logging: /HOME/.oemof/log_files
>>> logging.debug("Hallo")
``` 

The third line is ignored and so is the output in the fourth line. 

Maybe we will not have this problem again. If we do, this workaround is good enough.
