### ISSUE TITLE
oemof @ EUM-Fachtagung

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof_base#59]
This is only relevant for the ZNES side of oemof.

I think we should have a presentation on oemof at the "EUM-Fachtagung" which takes place from 31.3.-2.4. in Flensburg.

Session proposals so far:

* Globale Klimapolitik – Nachrichten aus Paris
* Klimaschutz in Entwicklungs- und Schwellenländern
* Lokaler Klimaschutz in der Praxis
* Energiewende, Postwachstumsökonomie und Industrie 4.0 - die Zukunftssession
* Mobilität – aktueller Stand, Konzepte, in der Modellierung(?) und NN...
* Energieeffizienz – Gebäudetechnik, ENEV Prozess, EEWärmeG und NN…
* Netze – AregV, Regulierungsmanagement, Netzentwicklungsplan 2025, Verteilnetze
* Strommarkt – Weißbuch und EnWG Novelle
* Strommarkt Praxis – Ausschreibungen, Direktvermarktung, Handel
* Open Power Systems & Data – neues aus dem ZNES ;)
* Virtuelle Kraftwerke in der Praxis
* Exkursionen/Firmenbesichtigungen (am Freitag!)
* Weitere….

I guess "Open Power Systems & Data – neues aus dem ZNES" would be perfect. 

From my side, I would offer myself for the presentation. But another additional person would be great!

@simonhilpert @wolfbunke @cswh

What do you think?

**Comment by ckaldemeyer** [comment]
@simonhilpert : If you're also keen I don't want to steal your show :D

**Comment by simonhilpert** [comment]
what show? We can do it together if you like. The pyomo-fest presentation will be there anyway, so 
we could build on that ....

**Comment by simonhilpert** [comment]
if it makes sense...if not i dont want to steal your show :smile:

**Comment by ckaldemeyer** [comment]
:D O.k., so I'll let Larissa know that we'll present something!

**Comment by simonhilpert** [comment]
By the way: Is this something we should create issues for ? (I think no...)

**Comment by ckaldemeyer** [comment]
Why not? If it could become a longer discussion I would say yes.

**Comment by simonhilpert** [comment]
because I think it is not an oemof but an ZNES topic, so we should discuss this rather on/in redmine

**Comment by ckaldemeyer** [comment]
Ah, o.k. I agree!

It's just that I don't like redundant structures and prefer github atm. But you're right..
