### ISSUE TITLE
solver output changed

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#62]
It seems to me that since commit bd9fd8fe the solver output changed.

Before this commit it was possible to use `stream_solver_output=True` to get the full solver output.
Now it doesn't work any more.

**Comment by simonhilpert** [comment]
This argument was removed for the optimize - method. The idea was to keep the optimize method and 
the simulation object lean and general. That is why it was replaced by the verbose attribute which only
prints out general information. 
If you want to stream the solver-output in the console you could do this by passing standard pyomo
arguments to the pyomo solve method via solve_kwargs in the OptimizationModel solve method, e.g. 'tee': 

optimization_model.solve(...,solve_kwargs={'tee':True})

**Comment by uvchik** [comment]
I had to change some things (ae866f52), but now it works.

```python
simulation = es.Simulation(
    solve_kwargs={'tee': True},
    timesteps=range(len(time_index)), verbose=True, solver='glpk',
    objective_options={'function': predefined_objectives.minimize_cost})
```

**Comment by simonhilpert** [comment]
This was actually I wanted to avoid, but let us keep it for now... we should think how we can keep the simulation object for general purposes, e.g. for different solver libraries and not a front-end for solph only...

**Comment by uvchik** [comment]
But for me it is still open for different solver libraries. You can just pass a parameter to the solver library. If you want to use polph for example which is based on pulp, you can pass a parameter to pulp.

I know the parameters are different but this could also be for the solver and/or the objective_options.
