### ISSUE TITLE
Design of logging messages.

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#64]
According to commit 47532fb4ca I would prefer if the logging message would only include the message and not further informations like module name etc. If you want these informations you better configure you `logging.ini`

```diff
- logging.info('Solph: Building component constraints.')
+ logging.info('Building component constraints.')
```

Than you can change the Formatter in the ini-file:
```diff
- format=%(asctime)s-%(levelname)s-%(message)s
+ format=%(asctime)s-%(levelname)s-%(module)s-%(message)s
```

This returns the module and not the package but you can find more attributes at:
https://docs.python.org/2/library/logging.html#logrecord-attributes

I think it is more individual like this. Everybody can decide what he/she wants to see.

**Comment by simonhilpert** [comment]
Ok I adapted the logging messages in solph...

**Comment by uvchik** [comment]
Thank you. The commit is quit big, so it is difficult to see the changes but everything seems okay.
