### ISSUE TITLE
solph-fast-build

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#66]
What is this about?

If you do fancy thing you should create an issue. Otherwise people like me will not notice and/or understand.

**Comment by simonhilpert** [comment]
We implemented  a different way of constraint building which should generally be faster as the standard pyomo way. It's only for most the important constraints for now. I will put infos in the whatsnew file. 

you can use this by setting the simulation class attribute `fast_build` to True

**Comment by uvchik** [comment]
Info in `whatsnew` is good but it is more important in the documentation.

Why is it faster? 
Is is it possible to create all constraints the fast way? 
Shouldn't we switch to the fast way until release x.x.x.?

**Comment by simonhilpert** [comment]
Basically it is possible to create all constraints in this way. If constraints get more complex, this 'workaround' can be a little bit more complicated, but still faster. 
We use a lot of non-public attributes of pyomo and skip some internal pyomo stuff. I am not sure
if all functionalities of pyomo models will still be available with the not standard way. Thats why I like 
to keep both way parallel. 
E.g. Pyomo might change the internal structure and our way would not be possible anymore...

**Comment by ckaldemeyer** [comment]
> We use a lot of non-public attributes of pyomo and skip some internal pyomo stuff. I am not sure
if all functionalities of pyomo models will still be available with the not standard way. Thats why I like
to keep both ways parallel.

There's probably a reason why it it's not the Pyomo standard implementation. Maybe it lowers the possible abstraction level. I gues this is a good topic for the Pyomo fest in Aachen ;)

**Comment by uvchik** [comment]
> I gues this is a good topic for the Pyomo fest in Aachen ;)

:+1: 

Thank you for the information.
