### ISSUE TITLE
Finalize Readme

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof_base#7]

**Comment by ckaldemeyer** [comment]
"Oemof stands for "Open Energy System Modeling Framework" and provides a free, open source and clearly documented model to analyse energy supply systems, developed in Python. It is designed as a framework with a modular structure and has several packages which communicate through well defined interfaces."

I like the text except for ", developed in Python" in  the first sentence. This sounds a bit heavy-handed to me.

What about:

"Oemof stands for "Open Energy System Modeling Framework" and provides a free, open source and clearly documented model to analyse energy supply systems. It is developed in Python and designed as a framework with a modular structure containing several packages which communicate through well defined interfaces."

Cheers
Cord

**Comment by uvchik** [comment]
Cords comment is related to #8.

**Comment by caro-rli** [comment]
This really sounds better. Thank you, Cord. Will change it in the readme file.

**Comment by caro-rli** [comment]
Does anyone know in which branch to adjust the readme file? It can be seen as a hotfix, can't it? Thus, it's the master branch? Not that familiar with the branching model yet... (and afraid of making any mistakes in public ;-) )

**Comment by uvchik** [comment]
I would say, the easiest thing is to create a fix branch and merge it into the dev and master branch after all changes are done.

**Comment by uvchik** [comment]
I have some comments to the readme file:

1. To install the developer version two steps are necessary:

    ```bash
    git clone git@github.com:oemof/oemof_base.git
    pip3 install -e /path/to/the/repository
    ```
2. I think contributing and developing are more or less the same. So I would join the paragraphs.

3. The code how to install oemof_base is under the section "Usage".

4. Fix the line `pip3 install oemof_base`. Now its just oemof.

**Comment by caro-rli** [comment]
Thanks for the comments. I did some enhancement, so far only in the master branch. If there are any more ideas for improvement, please post it here. Otherwise I'll close the issue in a few days.

**Comment by ckaldemeyer** [comment]
Looks good to me! I'm fine with the changes. Thanks, Caro!

**Comment by uvchik** [comment]
Looks good to me. Thanks @caro-rli.
