### ISSUE TITLE
Titles oemof and oemof/oemof_base

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof_base#8]
Hello on github ;-)

Here's my first issue on the titles which I don't find suitable:

"Model of an energy supply system as open framework with modular structure."  (oemof)

"open energy modelling framework - an open source model to optimise energy systems" (oemof/oemof_base)

For me oemof is not a model of one (or more) energy supply systems or a model to optimise energy systems but empowers the users to model (different parts) of energy supply systems and optionally provides the possibility to optimise them.

What do you think? I'll make up my mind meanwhile..

**Comment by ckaldemeyer** [comment]
Here are my proposals:

"Open Energy Modelling Framework - A modular open source framework to model energy supply systems" (oemof)

"Open Energy Modelling Framework - Base packages for energy system modeling and optimization" (oemof/oemof_base)

**Comment by uvchik** [comment]
I like the first one.

**Comment by caro-rli** [comment]
I like the first one, too. By the way, what about the spelling of "Modelling". In the logo we spell it with one 'l'.

**Comment by caro-rli** [comment]
Ah, got it.. I think, Cord made suggestions for both, oemof and oemof_base.. I like both.

**Comment by ckaldemeyer** [comment]
Good point. We should decide on that. I guess on RLI-side you are using British English as Uwe told me. But maybe we should go with the most common (American) which is also used by the openmod-initiative..

By the way I made some advertising in Düsseldorf ;)

**Comment by ckaldemeyer** [comment]
The landing page still says "open energy modelling framework - an open source model to optimise energy systems".

As Caro wrote I made suggestions for both, the first for the landing page and the second for oemof_base.

**Comment by ckaldemeyer** [comment]
But feel free to make other suggestions

**Comment by ckaldemeyer** [comment]
Do I need admin rights for the project to make title changes?  I just tried but couldn't find a button/link

**Comment by cswh** [comment]
Could we use some notifaction system if a decision is wanted?

e.g. Response needed from @gnn, @simonhilpert

**Comment by simonhilpert** [comment]
i like the first one too

**Comment by ckaldemeyer** [comment]
Yep, hat would be great. Or is it even possible to have a poll?

@simonhilpert : These are two suggestions, one for the user group title (github.com/oemof and one for oemof_base)
@cswh : So you are already fine with the suggestions?

**Comment by ckaldemeyer** [comment]
So its not either or ;)

**Comment by cswh** [comment]
Landing page and oemof_base proposals look good. I think in general it would be good if there are more owner do the oemof group for making changes. Can Cord become owner with admin right for the beginning?

**Comment by ckaldemeyer** [comment]
As Caro mentioned, another decision has to be made about the spelling. Are we using BR or AM English?

This is quite fundemental  and  should be written down in the documentation part  "How to document?"

I'll create a new issue for it..

**Comment by ckaldemeyer** [comment]
The rights seem to work, thanks. But somehow I cannot change the organisation title.

**Comment by ckaldemeyer** [comment]
Meaning not the title but the description on https://github.com/oemof :

"open energy modelling framework - an open source model to optimise energy systems"

**Comment by uvchik** [comment]
Done :smile:
